# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# To retrigger a rescan before the configured interval, you may touch this file, or hit the "check for update"
# in github UI on the last dependabot log screen

version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"


  - package-ecosystem: "gitsubmodule"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

# Dep is undocumented in github integration at https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#package-ecosystem
# but historically supported in dependabot-core at https://github.com/dependabot/dependabot-core/tree/main/dep/spec/dependabot/dep
  - package-ecosystem: "dep"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
